apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: apps
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=
  username: YWRtaW51c2Vy
  APPLICATION_KEY: QmllbnZlbmlkb3MgYWwgM2VyIG1lZXR1cCEhIHZhbG9yIHNlY3JldG8hISE=