apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-configmap
  namespace: apps
data:
  default.conf: |-
    server {
      listen       80;
      server_name  localhost;
      charset      utf-8;
      tcp_nopush   on;
      tcp_nodelay  on;
      server_tokens off;

      location / {
          root   /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
          index  index.html;
      }
    }
